//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeleSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find_location.
        /// </summary>
        internal static string Action_FindLocation {
            get {
                return ResourceManager.GetString("Action_FindLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record_audio.
        /// </summary>
        internal static string Action_RecordAudio {
            get {
                return ResourceManager.GetString("Action_RecordAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record_video.
        /// </summary>
        internal static string Action_RecordVideo {
            get {
                return ResourceManager.GetString("Action_RecordVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typing.
        /// </summary>
        internal static string Action_typing {
            get {
                return ResourceManager.GetString("Action_typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload_audio.
        /// </summary>
        internal static string Action_UploadAudio {
            get {
                return ResourceManager.GetString("Action_UploadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload_document.
        /// </summary>
        internal static string Action_UploadDocument {
            get {
                return ResourceManager.GetString("Action_UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload_photo.
        /// </summary>
        internal static string Action_UploadPhoto {
            get {
                return ResourceManager.GetString("Action_UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload_video.
        /// </summary>
        internal static string Action_UploadVideo {
            get {
                return ResourceManager.GetString("Action_UploadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio.
        /// </summary>
        internal static string AudioFile {
            get {
                return ResourceManager.GetString("AudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        internal static string DocumentFile {
            get {
                return ResourceManager.GetString("DocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type.
        /// </summary>
        internal static string HttpContentType {
            get {
                return ResourceManager.GetString("HttpContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multipart/form-data.
        /// </summary>
        internal static string HttpMultiPartFormData {
            get {
                return ResourceManager.GetString("HttpMultiPartFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answerCallbackQuery.
        /// </summary>
        internal static string Method_AnswerCallbackQuery {
            get {
                return ResourceManager.GetString("Method_AnswerCallbackQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answerInlineQuery.
        /// </summary>
        internal static string Method_AnswerInlineQuery {
            get {
                return ResourceManager.GetString("Method_AnswerInlineQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editMessageText.
        /// </summary>
        internal static string Method_EditMessageText {
            get {
                return ResourceManager.GetString("Method_EditMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forwardMessage.
        /// </summary>
        internal static string Method_ForwardMessage {
            get {
                return ResourceManager.GetString("Method_ForwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getFile.
        /// </summary>
        internal static string Method_GetFile {
            get {
                return ResourceManager.GetString("Method_GetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getMe.
        /// </summary>
        internal static string Method_GetMe {
            get {
                return ResourceManager.GetString("Method_GetMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getUpdates.
        /// </summary>
        internal static string Method_GetUpdates {
            get {
                return ResourceManager.GetString("Method_GetUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getUserProfilePhotos.
        /// </summary>
        internal static string Method_GetUserProfilePhotos {
            get {
                return ResourceManager.GetString("Method_GetUserProfilePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendAudio.
        /// </summary>
        internal static string Method_SendAudio {
            get {
                return ResourceManager.GetString("Method_SendAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendChatAction.
        /// </summary>
        internal static string Method_SendChatAction {
            get {
                return ResourceManager.GetString("Method_SendChatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendDocument.
        /// </summary>
        internal static string Method_SendDocument {
            get {
                return ResourceManager.GetString("Method_SendDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendLocation.
        /// </summary>
        internal static string Method_SendLocation {
            get {
                return ResourceManager.GetString("Method_SendLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendMessage.
        /// </summary>
        internal static string Method_SendMessage {
            get {
                return ResourceManager.GetString("Method_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendPhoto.
        /// </summary>
        internal static string Method_SendPhoto {
            get {
                return ResourceManager.GetString("Method_SendPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendSticker.
        /// </summary>
        internal static string Method_SendSticker {
            get {
                return ResourceManager.GetString("Method_SendSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sendVideo.
        /// </summary>
        internal static string Method_SendVideo {
            get {
                return ResourceManager.GetString("Method_SendVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action.
        /// </summary>
        internal static string Param_Action {
            get {
                return ResourceManager.GetString("Param_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cache_time.
        /// </summary>
        internal static string Param_CacheTime {
            get {
                return ResourceManager.GetString("Param_CacheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to callback_query_id.
        /// </summary>
        internal static string Param_CallbackQueryId {
            get {
                return ResourceManager.GetString("Param_CallbackQueryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caption.
        /// </summary>
        internal static string Param_Caption {
            get {
                return ResourceManager.GetString("Param_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chat_id.
        /// </summary>
        internal static string Param_ChatId {
            get {
                return ResourceManager.GetString("Param_ChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable_web_page_preview.
        /// </summary>
        internal static string Param_DisableWebPagePreview {
            get {
                return ResourceManager.GetString("Param_DisableWebPagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file_id.
        /// </summary>
        internal static string Param_FileId {
            get {
                return ResourceManager.GetString("Param_FileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from_chat_id.
        /// </summary>
        internal static string Param_FromChatId {
            get {
                return ResourceManager.GetString("Param_FromChatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inline_message_id.
        /// </summary>
        internal static string Param_InlineMessageId {
            get {
                return ResourceManager.GetString("Param_InlineMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inline_query_id.
        /// </summary>
        internal static string Param_InlineQueryid {
            get {
                return ResourceManager.GetString("Param_InlineQueryid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is_personal.
        /// </summary>
        internal static string Param_IsPersonal {
            get {
                return ResourceManager.GetString("Param_IsPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude.
        /// </summary>
        internal static string Param_Latitude {
            get {
                return ResourceManager.GetString("Param_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitude.
        /// </summary>
        internal static string Param_Longitude {
            get {
                return ResourceManager.GetString("Param_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message_id.
        /// </summary>
        internal static string Param_MessageId {
            get {
                return ResourceManager.GetString("Param_MessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next_offset.
        /// </summary>
        internal static string Param_NextOffset {
            get {
                return ResourceManager.GetString("Param_NextOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string Param_Offset {
            get {
                return ResourceManager.GetString("Param_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parse_mode.
        /// </summary>
        internal static string Param_ParseMode {
            get {
                return ResourceManager.GetString("Param_ParseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply_markup.
        /// </summary>
        internal static string Param_ReplyMarkup {
            get {
                return ResourceManager.GetString("Param_ReplyMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply_to_message_id.
        /// </summary>
        internal static string Param_ReplyToMmessageId {
            get {
                return ResourceManager.GetString("Param_ReplyToMmessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results.
        /// </summary>
        internal static string Param_Results {
            get {
                return ResourceManager.GetString("Param_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show_alert.
        /// </summary>
        internal static string Param_show_alert {
            get {
                return ResourceManager.GetString("Param_show_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string Param_Text {
            get {
                return ResourceManager.GetString("Param_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeout.
        /// </summary>
        internal static string Param_Timeout {
            get {
                return ResourceManager.GetString("Param_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to url.
        /// </summary>
        internal static string Param_url {
            get {
                return ResourceManager.GetString("Param_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user_id.
        /// </summary>
        internal static string Param_UserId {
            get {
                return ResourceManager.GetString("Param_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photo.
        /// </summary>
        internal static string PhotoFile {
            get {
                return ResourceManager.GetString("PhotoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sticker.
        /// </summary>
        internal static string StickerFile {
            get {
                return ResourceManager.GetString("StickerFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.telegram.org/bot.
        /// </summary>
        internal static string TelegramAPIUrl {
            get {
                return ResourceManager.GetString("TelegramAPIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.telegram.org/file/bot{0}/{1}.
        /// </summary>
        internal static string TelegramDownloadDocumentUrl {
            get {
                return ResourceManager.GetString("TelegramDownloadDocumentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded ; charset=UTF-8.
        /// </summary>
        internal static string TeleSharpHttpClientContentType {
            get {
                return ResourceManager.GetString("TeleSharpHttpClientContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video.
        /// </summary>
        internal static string VideoFile {
            get {
                return ResourceManager.GetString("VideoFile", resourceCulture);
            }
        }
    }
}
